version: v1

labels:
  - label: "feat"
    matcher:
      title: "^feat:.*"
  - label: "fix"
    matcher:
      title: "^fix:.*"
  - label: "chore"
    matcher:
      title: "^chore:.*"
  - label: "docs"
    matcher:
      title: "^docs:.*"
  - label: "dependencies"
    matcher:
      title: "^chore(deps):.*"

checks:
  - context: "Semantic Pull Request"
    url: "https://github.com/settlemint/docs/blob/main/.github/labeler.yml"
    description:
      success: Ready for review & merge.
      failure: Missing semantic label for merge.
    labels:
      any:
        - feat
        - fix
        - chore
        - docs
        - dependencies
