/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "SettleMint Developer Hub",
  "tagline": "The Blockchain Transformation Platform for developers to rapidly build blockchain applications",
  "url": "https://console.settlemint.com",
  "baseUrl": "/documentation/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "throw",
  "trailingSlash": true,
  "favicon": "img/favicon.ico",
  "organizationName": "settlemint",
  "projectName": "btp-docs",
  "plugins": [
    "/Users/saeeddawod/Desktop/docs/node_modules/docusaurus-lunr-search/src/index.js",
    [
      "@docusaurus/plugin-content-blog",
      {
        "id": "releases",
        "routeBasePath": "releases",
        "path": "./releases",
        "blogSidebarCount": "ALL",
        "onUntruncatedBlogPosts": "ignore"
      }
    ],
    [
      "@docusaurus/plugin-ideal-image",
      {
        "quality": 70,
        "max": 1030,
        "min": 640,
        "steps": 2,
        "disableInDev": false
      }
    ],
    "/Users/saeeddawod/Desktop/docs/src/plugins/docusaurus-llms-plugin"
  ],
  "presets": [
    [
      "classic",
      {
        "sitemap": {
          "lastmod": "date",
          "changefreq": "weekly",
          "priority": 0.5,
          "ignorePatterns": [
            "/tags/**"
          ],
          "filename": "sitemap.xml"
        },
        "docs": {
          "sidebarPath": "/Users/saeeddawod/Desktop/docs/sidebars.ts"
        },
        "gtag": {
          "trackingID": "G-N1MMHFDVZZ",
          "anonymizeIP": false
        },
        "blog": {
          "showReadingTime": true,
          "blogTitle": "Developer Blog",
          "sortPosts": "descending",
          "onUntruncatedBlogPosts": "ignore"
        },
        "theme": {
          "customCss": "/Users/saeeddawod/Desktop/docs/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "navbar": {
      "title": "",
      "logo": {
        "alt": "SettleMint",
        "src": "img/settlemint-hub-black.png",
        "srcDark": "img/settlemint-hub-white.png"
      },
      "items": [
        {
          "type": "doc",
          "docId": "about-settlemint/intro",
          "position": "left",
          "label": "Docs"
        },
        {
          "to": "/docs/developer-guides/guide-library",
          "label": "Guides",
          "position": "left"
        },
        {
          "to": "/blog/",
          "label": "Developer Blog",
          "position": "left"
        },
        {
          "href": "/releases",
          "label": "Releases",
          "position": "right"
        },
        {
          "href": "https://settlemint.com",
          "label": "Website",
          "position": "right"
        },
        {
          "href": "https://console.settlemint.com/documentation/llms.txt",
          "label": "llms.txt",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "About SettleMint",
              "to": "/docs/about-settlemint/intro"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "SettleMint Platform",
              "href": "https://console.settlemint.com"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/settlemintcom"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Developer Blog",
              "to": "/blog"
            },
            {
              "label": "Website",
              "href": "https://settlemint.com"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 SettleMint."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "solidity"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "future": {
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
