name: Branch

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

env:
  NODE_NO_WARNINGS: "1"
  TURBO_TELEMETRY_DISABLED: "1"

jobs:
  build:
    name: Build
    runs-on: namespace-profile-btp-docs
    steps:
      - name: Checkout
        uses: namespacelabs/nscloud-checkout-action@v7
        with:
          fetch-depth: 2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: .nvmrc
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup caches
        uses: namespacelabs/nscloud-cache-action@449c929cd5138e6607e7e78458e88cc476e76f89 # v1
        with:
          path: |
            ~/.bun/install/cache
            ${{ github.workspace }}/.next/cache

      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
        with:
          bun-version-file: .bun-version

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install YQ
        uses: alexellis/arkade-get@master
        with:
          print-summary: false
          yq: latest

      - name: Install dependencies
        run: |
          bun install

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v5

      - name: Version
        id: version
        shell: bash
        run: |
          if [[ $GITHUB_REF_SLUG =~ ^v?[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            VERSION=$GITHUB_REF_SLUG
          else
            VERSION="7.0.0-${GITHUB_REF_SLUG}.${{ github.run_id }}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build
        run: |
          bun run build
        env:
          NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}

      - name: Build Docker container
        run: |
          bun run docker

  pr-labels:
    name: PR Labels
    if: github.event_name == 'pull_request'
    permissions:
      checks: write
      issues: write
      pull-requests: write
      statuses: write
      contents: read
    uses: settlemint/asset-tokenization-kit/.github/workflows/reusable-pr-labels.yml@main

  secret-scanning:
    name: Secret Scanning
    permissions:
      security-events: write
      contents: read
    uses: settlemint/asset-tokenization-kit/.github/workflows/reusable-secret-scanning.yml@main
    with:
      trivy-config: trivy-secret.yaml
      severity: "HIGH,CRITICAL"

  codeql:
    name: CodeQL
    permissions:
      security-events: write
      contents: read
      actions: read
      packages: read
    uses: settlemint/asset-tokenization-kit/.github/workflows/reusable-codeql.yml@main
    with:
      language: "javascript-typescript"
      build-mode: "none"

  slack-notification-start:
    name: Slack Notification (Start)
    if: github.event_name == 'pull_request'
    permissions:
      actions: read
      issues: write
      pull-requests: write
      contents: read
    uses: settlemint/asset-tokenization-kit/.github/workflows/reusable-slack-notification.yml@main
    with:
      workflow_conclusion: "running"
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

  slack-notification-end:
    name: Slack Notification (End)
    needs: [build, secret-scanning, codeql, pr-labels]
    if: always() && github.event_name == 'pull_request'
    permissions:
      actions: read
      issues: write
      pull-requests: write
      contents: read
    uses: settlemint/asset-tokenization-kit/.github/workflows/reusable-slack-notification.yml@main
    with:
      workflow_conclusion:
        ${{ needs.build.result == 'success' && needs.secret-scanning.result !=
        'failure' && needs.codeql.result != 'failure' && needs.pr-labels.result
        != 'failure' && 'success' || 'failure' }}
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
