name: Branch

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

env:
  NODE_NO_WARNINGS: '1'
  TURBO_TELEMETRY_DISABLED: '1'

jobs:
  build:
    name: Build
    runs-on: namespace-profile-btp-docs
    steps:
      - name: Checkout
        uses: namespacelabs/nscloud-checkout-action@v5
        with:
          fetch-depth: 2

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version-file: package.json
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup caches
        uses: namespacelabs/nscloud-cache-action@1d016dd6d40428050a16a6271307888386cc0bec # v1
        with:
          path: |
            .turbo
            ~/.bun/install/cache

      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
        with:
          bun-version-file: package.json

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install YQ
        uses: alexellis/arkade-get@master
        with:
          print-summary: false
          yq: latest

      - name: Install dependencies
        run: |
          bun install

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v5

      - name: Version
        id: version
        shell: bash
        run: |
          if [[ $GITHUB_REF_SLUG =~ ^v?[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            VERSION=$GITHUB_REF_SLUG
          else
            VERSION="7.0.0-${GITHUB_REF_SLUG}.${{ github.run_id }}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build
        run: |
          bun run build

      - name: Build Docker container
        run: |
          bun run docker

      - name: Cosign Docker container
        run: |
          bun run cosign
